services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - "RABBITMQ_DEFAULT_USER=guest"
      - "RABBITMQ_DEFAULT_PASS=guest"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 30s
      retries: 5

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: "service_healthy"
    environment:
      - "RABBITMQ_HOST=rabbitmq"
      - "RABBITMQ_PORT=5672"

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=trab_amqp"
